name: shifaa_pharmacy
description: Shifaa Pharmacy App
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #GetX
  get: ^4.1.4
  dio: ^4.0.0
  hive: ^2.0.4
  data_connection_checker: ^0.3.4
  shimmer: ^2.0.0
  cached_network_image: ^3.0.0
  auto_size_text: ^2.1.0
  injectable: ^1.3.0
  get_it: ^6.1.1

  #The Packages
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  http: ^0.13.1
  shared_preferences: ^2.0.5
  image_picker: ^0.7.4
  share: ^2.0.1
  url_launcher: ^6.0.3
  flutter_device_type: ^0.4.0
  flutter_speed_dial: ^3.0.5
  like_button: ^2.0.0
  intl: ^0.17.0
  flutter_spinkit: ^4.1.2+1
  email_validator: ^2.0.1
  modal_progress_hud: ^0.1.3
  flutter_html: ^1.3.0
  animated_splash_screen: ^1.1.0


dev_dependencies:
  freezed: ^0.14.1+3
  build_runner: ^2.0.1
  change_app_package_name: ^0.1.2
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
    - assets/